#!/bin/bash

docker run -it --rm -v "$(pwd):/app" --name search-service-lint search-service npm run lint
docker run -it --rm -v "$(pwd):/app" --name search-service-format search-service npm run format
